name: mask-align
dependencies:
  -          csvkit=1.0.7
  -          cudatoolkit=10.2
  -          nltk=3.6.2
  -          numpy
  -          python=3.9
  - pytorch::pytorch=1.8.1
  -          regex=2021.7.6
  -          sentencepiece
  -          six=1.15.0
  -          tensorflow=2.5.0
