▁ D os ▁de ▁los ▁principales ▁partidos ▁políticos ▁de ▁ T ur quí a ▁están ▁presionando ▁por ▁una ▁enmienda ▁constitucional ▁para ▁levantar ▁la ▁prohibición ▁de ▁los ▁ve los ▁en ▁las ▁universidades ▁públicas , ▁una ▁medida ▁que ▁ha ▁causado ▁preocupación ▁entre ▁la ▁población ▁la ica ▁de ▁ T ur quí a .
▁ L as ▁universidades ▁turcas ▁impusieron ▁prohibiciones ▁a ▁las ▁tapa s ▁de ▁la ▁cabeza ▁a ▁principios ▁de ▁la ▁década ▁de ▁1980 ▁porque ▁eran ▁visto s ▁como ▁símbolos ▁políticos ▁y ▁estaban ▁en ▁conflicto ▁con ▁el ▁sistema ▁de ▁gobierno ▁secular ▁de ▁ T ur quí a .
▁ L a ▁nave ▁que ▁transportaba ▁al ▁primer ▁a st ron au ta ▁de ▁ C o rea ▁del ▁ S ur ▁aterriz ó ▁en ▁el ▁norte ▁de ▁ K a za ji s tán ▁el ▁sábado , ▁a ▁4 18 ▁kilómetros ▁de ▁distancia , ▁dijeron .
▁ E n ▁octubre , ▁la ▁c á p sula ▁de ▁ S o y uz ▁aterriz ó ▁a ▁70 ▁kilómetros ▁de ▁la ▁zona ▁planeada ▁debido ▁a ▁un ▁cable ▁de ▁control ▁dañado . ▁ L a ▁c á p sula ▁transportaba ▁a ▁dos ▁co smo n au tas ▁rusos ▁y ▁al ▁primer ▁a st ron au ta ▁malas io .
▁ E sta ▁no ▁es ▁la ▁primera ▁vez ▁que ▁una ▁nave ▁espacial ▁se ▁desvía ▁de ▁su ▁trayectoria ▁planeada ▁durante ▁el ▁aterrizaje .
▁ L a ▁nave ▁que ▁transportaba ▁al ▁primer ▁a st ron au ta ▁de ▁ C o rea ▁del ▁ S ur ▁aterriz ó ▁en ▁el ▁norte ▁de ▁ K a za ji s tán ▁el ▁sábado , ▁a ▁4 18 ▁kilómetros ▁de ▁distancia , ▁dijeron .
▁ L a ▁renuncia ▁del ▁lunes ▁llegó ▁horas ▁después ▁de ▁que ▁la ▁ O rga n ización ▁ M und ial ▁de ▁la ▁ S al ud ▁dijera ▁que ▁el ▁escándalo ▁había ▁puesto ▁de ▁relieve ▁los ▁defectos ▁en ▁toda ▁la ▁cadena ▁de ▁suministro ▁de ▁alimentos ▁del ▁país .
▁ S eg ún ▁se ▁informa , ▁el ▁jefe ▁del ▁perro ▁guardián ▁de ▁la ▁calidad ▁de ▁ C h ina ▁re nunció ▁por ▁el ▁escándalo ▁de ▁la ▁leche ▁de ▁bebé ▁contaminada ▁que ▁ha ▁matado ▁a ▁cuatro ▁niños ▁y ▁en fer mó ▁a ▁otros ▁53 , 000 .
▁ E l ▁representante ▁de ▁la ▁ OMS ▁en ▁ C h ina , ▁ H an s ▁ T ro ed s son , ▁dijo ▁que ▁los ▁problemas ▁de ▁calidad ▁del ▁lunes ▁podrían ▁ocurrir ▁desde ▁la ▁granja ▁hasta ▁el ▁punto ▁de ▁venta ▁al ▁por ▁menor .
▁ S eg ún ▁se ▁informa , ▁el ▁jefe ▁del ▁perro ▁guardián ▁de ▁la ▁calidad ▁de ▁ C h ina ▁re nunció ▁por ▁el ▁escándalo ▁de ▁la ▁leche ▁de ▁bebé ▁contaminada ▁que ▁ha ▁matado ▁a ▁cuatro ▁niños ▁y ▁en fer mó ▁a ▁otros ▁53 , 000 .
▁ S eg ún ▁se ▁informa , ▁el ▁jefe ▁del ▁perro ▁guardián ▁de ▁la ▁calidad ▁de ▁ C h ina ▁re nunció ▁por ▁el ▁escándalo ▁de ▁la ▁leche ▁de ▁bebé ▁contaminada ▁que ▁ha ▁matado ▁a ▁cuatro ▁niños ▁y ▁en fer mó ▁a ▁otros ▁53 , 000 .
▁ L a ▁renuncia ▁del ▁lunes ▁llegó ▁horas ▁después ▁de ▁que ▁la ▁ O rga n ización ▁ M und ial ▁de ▁la ▁ S al ud ▁dijera ▁que ▁el ▁escándalo ▁había ▁puesto ▁de ▁relieve ▁los ▁defectos ▁en ▁toda ▁la ▁cadena ▁de ▁suministro ▁de ▁alimentos ▁del ▁país .
